general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock after 5 minutes of inactivity
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off displays after 20 minutes of inactivity
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
