return {}
-- return {
--   "yetone/avante.nvim",
--   event = "VeryLazy",
--   lazy = false,
--   priority = 1000, -- Load early since we're using lazy = false
--   version = false, -- Always pull the latest change
--   opts = {
--     ---@alias Provider "claude" | "openai" | "azure" | "gemini" | "cohere" | "copilot" | string
--     provider = "claude",
--     auto_suggestions_provider = "ollama", -- The provider to use for auto-suggestions
--     cursor_applying_provider = "ollama", -- The provider to use for cursor applying
--
--     ollama = {
--       endpoint = os.getenv("OLLAMA_ENDPOINT") or "http://localhost:11434",
--       model = "qwen2.5-coder:14b-instruct-q8_0",
--       disable_tools = true, -- Open-source models often do not support tools.
--     },
--     claude = {
--       endpoint = "https://api.anthropic.com",
--       model = "claude-3-5-sonnet-20241022",
--       temperature = 0, -- 0 for more deterministic responses
--       max_tokens = 4096,
--     },
--
--     -- Common options
--     show_prompt = true, -- Show the prompt in chat
--     show_model = true, -- Show which model is being used
--     auto_follow_cursor = true, -- Auto-scroll to follow cursor
--     clear_chat_on_new_prompt = false, -- Keep chat history between prompts
--
--     behaviour = {
--       auto_suggestions = false, -- Experimental stage
--       auto_set_highlight_group = true,
--       auto_set_keymaps = true,
--       auto_apply_diff_after_generation = false,
--       support_paste_from_clipboard = false,
--       minimize_diff = true, -- Remove unchanged lines when applying a code block
--       enable_token_counting = true, -- Enable token counting
--       enable_cursor_planning_mode = true, -- Enable Cursor Planning Mode
--       enable_claude_text_editor_tool_mode = false, -- Enable Claude Text Editor Tool Mode
--     },
--   },
--   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--   build = "make",
--   dependencies = {
--     "nvim-treesitter/nvim-treesitter",
--     "stevearc/dressing.nvim",
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     --- The below dependencies are optional,
--     -- "zbirenbaum/copilot.lua", -- for providers='copilot'
--     {
--       -- support for image pasting
--       "HakonHarnes/img-clip.nvim",
--       event = "VeryLazy",
--       opts = {
--         -- recommended settings
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           -- required for Windows users
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       -- Make sure to set this up properly if you have lazy=true
--       'MeanderingProgrammer/render-markdown.nvim',
--       opts = {
--         file_types = { "markdown", "Avante" },
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
-- }
