return {
  { 'AndrewRadev/splitjoin.vim' },
  { 'andymass/vim-matchup',            event = 'VeryLazy' },
  { 'christoomey/vim-tmux-runner' },
  { 'editorconfig/editorconfig-vim' },
  { 'godlygeek/tabular',               event = 'VeryLazy' },
  { 'haya14busa/is.vim' },
  { 'mattn/emmet-vim',                 event = 'VeryLazy' },
  { 'norcalli/nvim-colorizer.lua',     event = 'VeryLazy' },
  { 'pbrisbin/vim-mkdir' },
  { 'psliwka/vim-smoothie' },
  { 'stefandtw/quickfix-reflector.vim' },
  { 'tpope/vim-commentary' },
  { 'tpope/vim-fugitive',              event = 'VeryLazy' },
  { 'tpope/vim-repeat' },
  { 'tpope/vim-surround' },
  { 'windwp/nvim-autopairs',           opts = {} },
}
