#!/bin/sh

chosen=$(printf "  Lock\n  Suspend\n  Reboot\n  Shutdown\n󰍃  Log Off" | rofi -p "Session:" -dmenu -i)

case "$chosen" in
    "  Lock")    swaylock -c 000000 ;;
    "  Suspend") swaylock -c 000000 & systemctl suspend ;;
    "  Reboot")  systemctl reboot ;;
    "  Shutdown") systemctl poweroff ;;
    "󰍃  Log Off") mmsg -s -d quit ;;
    *) exit 1 ;;
esac
